/*
 * Copyright (c) 2024 Martin Bechard <martin.bechard@DevConsult.ca>
 * This software is licensed under the MIT License.
 * File: /Users/martinbechard/dev/mcp-perplexity/src/types/PerplexityConfig.ts
 * This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
 *
 * Configuration type definitions for the Perplexity API
 * Where flexibility meets control! 🎛️
 */

import { Message } from "./PerplexityTypes.js";

/**
 * Configuration type for Perplexity API chat completion requests.
 * Reference: https://docs.perplexity.ai/api-reference/chat-completions
 */
export type PerplexityConfig = {
  /** The name of the model to use for completion */
  model: string;

  /** Array of messages in the conversation */
  messages: Message[];

  /** Maximum number of tokens to generate. Uses model context limit if unspecified */
  maxTokens?: number;

  /** Controls randomness in the response (0 to 2) */
  temperature?: number;

  /** Alternative to temperature for nucleus sampling (0 to 1) */
  topP?: number;

  /** List of domains to filter citations by */
  searchDomainFilter?: string[];

  /** Whether to return images in the response */
  returnImages?: boolean;

  /** Whether to return related questions */
  returnRelatedQuestions?: boolean;

  /** Time interval for search results filtering */
  searchRecencyFilter?: "month" | "week" | "day" | "hour";

  /** Number of tokens for top-k filtering (0 to 2048) */
  topK?: number;

  /** Whether to stream the response */
  stream?: boolean;

  /** Penalize new tokens based on presence (-2.0 to 2.0) */
  presencePenalty?: number;

  /** Penalize new tokens based on frequency (greater than 0) */
  frequencyPenalty?: number;
};
